/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

typedef struct {
	BOOL _field1;
	BOOL _field2;
	BOOL _field3;
	float _field4;
	int _field5;
	float _field6;
} XXStruct_3B_lsC;

typedef struct __GSEvent* GSEventRef;

typedef struct __darwin_pthread_handler_rec darwin_pthread_handler_rec;

typedef struct __CTCall* CTCallRef;

typedef struct _MISProfile* MISProfileRef;

typedef struct {
	unsigned _field1[8];
} XXStruct_kUSYWB;

typedef struct {
	int _field1;
	int _field2;
} XXStruct_K5nmsA;

typedef struct __CTServerConnection* CTServerConnectionRef;

typedef struct __WiFiManagerClient WiFiManagerClient;

typedef struct __WiFiDeviceClient WiFiDeviceClient;

typedef struct __WiFiNetwork WiFiNetwork;


typedef struct {
	unsigned char voicemailAvailable;
	int voicemailCount;
	long long voicemailID;
} XXStruct_EX3dgA;

typedef struct {
	int _field1;
	BOOL _field2;
	BOOL _field3;
	BOOL _field4;
	BOOL _field5;
	double _field6;
} XXStruct_fhKmAA;


typedef struct CalEventExpirationMonitor CalEventExpirationMonitor;

typedef struct CalAlarmEngine CalAlarmEngine;

typedef struct CalDatabase CalDatabase;

typedef struct dispatch_queue_s dispatch_queue_s;

typedef struct dispatch_source_s dispatch_source_s;

typedef struct SBProcessTimes {
	double execTime;
	double beginUserCPUElapsedTime;
	double beginSystemCPUElapsedTime;
	double beginIdleCPUElapsedTime;
	double beginApplicationCPUElapsedTime;
} SBProcessTimes;


